// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CVSSVectorBreakdown c v s s vector breakdown
//
// swagger:model CVSSVectorBreakdown
type CVSSVectorBreakdown struct {

	// access complexity
	AccessComplexity AccessComplexity `json:"accessComplexity,omitempty"`

	// access vector
	AccessVector AccessVector `json:"accessVector,omitempty"`

	// attack complexity
	AttackComplexity AttackComplexity `json:"attackComplexity,omitempty"`

	// attack vector
	AttackVector AttackVector `json:"attackVector,omitempty"`

	// authentication
	Authentication Authentication `json:"authentication,omitempty"`

	// availability
	Availability Availability `json:"availability,omitempty"`

	// confidentiality
	Confidentiality Confidentiality `json:"confidentiality,omitempty"`

	// integrity
	Integrity Integrity `json:"integrity,omitempty"`

	// privileges required
	PrivilegesRequired PrivilegesRequired `json:"privilegesRequired,omitempty"`

	// scope
	Scope Scope `json:"scope,omitempty"`

	// user interaction
	UserInteraction UserInteraction `json:"userInteraction,omitempty"`
}

// Validate validates this c v s s vector breakdown
func (m *CVSSVectorBreakdown) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessComplexity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccessVector(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAttackComplexity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAttackVector(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAuthentication(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAvailability(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConfidentiality(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIntegrity(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivilegesRequired(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserInteraction(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CVSSVectorBreakdown) validateAccessComplexity(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessComplexity) { // not required
		return nil
	}

	if err := m.AccessComplexity.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("accessComplexity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateAccessVector(formats strfmt.Registry) error {
	if swag.IsZero(m.AccessVector) { // not required
		return nil
	}

	if err := m.AccessVector.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("accessVector")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateAttackComplexity(formats strfmt.Registry) error {
	if swag.IsZero(m.AttackComplexity) { // not required
		return nil
	}

	if err := m.AttackComplexity.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("attackComplexity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateAttackVector(formats strfmt.Registry) error {
	if swag.IsZero(m.AttackVector) { // not required
		return nil
	}

	if err := m.AttackVector.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("attackVector")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateAuthentication(formats strfmt.Registry) error {
	if swag.IsZero(m.Authentication) { // not required
		return nil
	}

	if err := m.Authentication.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("authentication")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateAvailability(formats strfmt.Registry) error {
	if swag.IsZero(m.Availability) { // not required
		return nil
	}

	if err := m.Availability.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("availability")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateConfidentiality(formats strfmt.Registry) error {
	if swag.IsZero(m.Confidentiality) { // not required
		return nil
	}

	if err := m.Confidentiality.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidentiality")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateIntegrity(formats strfmt.Registry) error {
	if swag.IsZero(m.Integrity) { // not required
		return nil
	}

	if err := m.Integrity.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("integrity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validatePrivilegesRequired(formats strfmt.Registry) error {
	if swag.IsZero(m.PrivilegesRequired) { // not required
		return nil
	}

	if err := m.PrivilegesRequired.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("privilegesRequired")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateScope(formats strfmt.Registry) error {
	if swag.IsZero(m.Scope) { // not required
		return nil
	}

	if err := m.Scope.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("scope")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) validateUserInteraction(formats strfmt.Registry) error {
	if swag.IsZero(m.UserInteraction) { // not required
		return nil
	}

	if err := m.UserInteraction.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("userInteraction")
		}
		return err
	}

	return nil
}

// ContextValidate validate this c v s s vector breakdown based on the context it is used
func (m *CVSSVectorBreakdown) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessComplexity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAccessVector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAttackComplexity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAttackVector(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAuthentication(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAvailability(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateConfidentiality(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIntegrity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePrivilegesRequired(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUserInteraction(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAccessComplexity(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AccessComplexity.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("accessComplexity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAccessVector(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AccessVector.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("accessVector")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAttackComplexity(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AttackComplexity.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("attackComplexity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAttackVector(ctx context.Context, formats strfmt.Registry) error {

	if err := m.AttackVector.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("attackVector")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAuthentication(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Authentication.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("authentication")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateAvailability(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Availability.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("availability")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateConfidentiality(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Confidentiality.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("confidentiality")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateIntegrity(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Integrity.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("integrity")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidatePrivilegesRequired(ctx context.Context, formats strfmt.Registry) error {

	if err := m.PrivilegesRequired.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("privilegesRequired")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateScope(ctx context.Context, formats strfmt.Registry) error {

	if err := m.Scope.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("scope")
		}
		return err
	}

	return nil
}

func (m *CVSSVectorBreakdown) contextValidateUserInteraction(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UserInteraction.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("userInteraction")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CVSSVectorBreakdown) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CVSSVectorBreakdown) UnmarshalBinary(b []byte) error {
	var res CVSSVectorBreakdown
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
